exports.seed = function (knex) {
  return knex("event")
    .del()
    .then(function () {
      return knex("event").insert([
        {
          eventName: null,
          contractAddress: "0xff57abade2be75295468412507e98fd0fea66ff9",
          eventLocation: "Haiti",
          eventPhoto:
            "https://res.cloudinary.com/dnq92mpxr/image/upload/v1627366927/icons/christopher-gower-m_HRfLhgABo-unsplash_nxr0x0.jpg",
          eventDescription: null,
          eventDate: "2020-09-25 06:29:53",
          startTime: "6:46 PM",
          endTime: "7:54 AM",
          eventCapacity: 562,
          venue: "Hong Kong Coliseum",
          eventType: "educational",
          isOnline: false,
          users_id: 10,
        },
        {
          eventName: null,
          contractAddress: "0x8ad47edc4f104c79e9aab0ddd6fbe89e0d9447b2",
          eventLocation: "Kazakhstan",
          eventPhoto:
            "https://res.cloudinary.com/dnq92mpxr/image/upload/v1627366928/icons/carl-barcelo-nqUHQkuVj3c-unsplash-min_g0dfg5.jpg",
          eventDescription: null,
          eventDate: "2021-03-25 02:17:32",
          startTime: "6:52 PM",
          endTime: "3:38 AM",
          eventCapacity: 562,
          venue: "Hong Kong Coliseum",
          eventType: "concert",
          isOnline: false,
          users_id: 1,
        },
        {
          eventName: null,
          contractAddress: "0x7ebfc798585edc9b0b88b5a8dd86b1e1c00c0523",
          eventLocation: "Russia",
          eventPhoto:
            "https://res.cloudinary.com/dnq92mpxr/image/upload/v1627366928/icons/teemu-paananen-bzdhc5b3Bxs-unsplash-min_gn5jhw.jpg",
          eventDescription: null,
          eventDate: "2020-11-01 12:16:14",
          startTime: "6:29 PM",
          endTime: "6:03 PM",
          eventCapacity: 562,
          venue: "Hong Kong Coliseum",
          eventType: "hobbies",
          isOnline: false,
          users_id: 2,
        },
        {
          eventName: null,
          contractAddress: "0x986d602d1e1d9ebaf5ae21702c6aaaa4d4280de9",
          eventLocation: "Indonesia",
          eventPhoto:
            "https://res.cloudinary.com/dnq92mpxr/image/upload/v1627366928/icons/zachary-smith-DgBNkXB-ckI-unsplash-min_hld9bh.jpg",
          eventDescription: null,
          eventDate: "2021-03-15 17:37:53",
          startTime: "6:09 PM",
          endTime: "10:29 AM",
          eventCapacity: 897,
          venue: "AsiaWorld-Expo",
          eventType: "educational",
          isOnline: false,
          users_id: 2,
        },
        {
          eventName: null,
          contractAddress: null,
          eventLocation: "Thailand",
          eventPhoto:
            "https://res.cloudinary.com/dnq92mpxr/image/upload/v1627366928/icons/conscious-design-3D43SBDDkAc-unsplash-min_jb8tbg.jpg",
          eventDescription: null,
          eventDate: "2021-07-15 15:22:01",
          startTime: "7:46 PM",
          endTime: "1:55 PM",
          eventCapacity: 2000,
          venue: null,
          eventType: "concert",
          isOnline: true,
          users_id: 5,
        },
        {
          eventName: null,
          contractAddress: "0xa157dca33967db3abc62efb37f1683ed40eca7de",
          eventLocation: "Jordan",
          eventPhoto:
            "https://res.cloudinary.com/dnq92mpxr/image/upload/v1627366929/icons/stem-list-EVgsAbL51Rk-unsplash-min_cxjrb6.jpg",
          eventDescription: null,
          eventDate: "2020-08-19 01:26:42",
          startTime: "7:19 PM",
          endTime: "8:04 AM",
          eventCapacity: 562,
          venue: "Hong Kong Coliseum",
          eventType: "musical",
          isOnline: false,
          users_id: 3,
        },
        {
          eventName: null,
          contractAddress: null,
          eventLocation: "United Arab Emirates",
          eventPhoto:
            "https://res.cloudinary.com/dnq92mpxr/image/upload/v1627366931/icons/roman-hinex-3s-D6FZKxAc-unsplash-min_gkye2c.jpg",
          eventDescription: null,
          eventDate: "2020-09-29 10:09:30",
          startTime: "7:38 PM",
          endTime: "5:29 AM",
          eventCapacity: null,
          venue: "AsiaWorld-Expo",
          eventType: "musical",
          isOnline: false,
          users_id: 3,
        },
        {
          eventName: null,
          contractAddress: "0x7ebfc798585edc9b0b88b5a8dd86b1e1c00c0523",
          eventLocation: "Japan",
          eventPhoto:
            "https://res.cloudinary.com/dnq92mpxr/image/upload/v1627366931/icons/hanny-naibaho-aWXVxy8BSzc-unsplash-min_wlwgbv.jpg",
          eventDescription: null,
          eventDate: "2020-10-18 01:26:49",
          startTime: "6:21 PM",
          endTime: "4:46 PM",
          eventCapacity: 897,
          venue: "AsiaWorld-Expo",
          eventType: "educational",
          isOnline: false,
          users_id: 6,
        },
        {
          eventName: null,
          contractAddress: "0x32f8c216be5e0f71a0f4854e6da16c286f486791",
          eventLocation: "Bermuda",
          eventPhoto:
            "https://res.cloudinary.com/dnq92mpxr/image/upload/v1627367003/icons/fabio-silva-nmTm7knUnqs-unsplash_ccyekw.jpg",
          eventDescription: null,
          eventDate: "2020-12-16 16:21:23",
          startTime: "6:24 PM",
          endTime: "10:37 PM",
          eventCapacity: 562,
          venue: "Hong Kong Coliseum",
          eventType: "musical",
          isOnline: false,
          users_id: 2,
        },
        {
          eventName: null,
          contractAddress: "0x271e12b79fd174ed575cf0e971e6c1cb55b7f379",
          eventLocation: "China",
          eventPhoto:
            "https://res.cloudinary.com/dnq92mpxr/image/upload/v1627367044/icons/sam-mcghee-4siwRamtFAk-unsplash_l1k5a3.jpg",
          eventDescription: null,
          eventDate: "2021-01-30 04:30:52",
          startTime: "7:30 PM",
          endTime: "11:51 AM",
          eventCapacity: 897,
          venue: "AsiaWorld-Expo",
          eventType: "concert",
          isOnline: false,
          user_id: 8,
        },
      ]);
    });
};
